package org.example.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-13T17:22:42.094-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "QueueLogService",
                  wsdlLocation = "file:/D:/oxygen/eclipse-workspace/QueueLogService/src/main/resources/wsdl/queuelog.wsdl",
                  targetNamespace = "http://www.example.org/demo/")
public class QueueLogService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/demo/", "QueueLogService");
    public final static QName QueueLogServicesEndpoint = new QName("http://www.example.org/demo/", "QueueLogServicesEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/oxygen/eclipse-workspace/QueueLogService/src/main/resources/wsdl/queuelog.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueueLogService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/oxygen/eclipse-workspace/QueueLogService/src/main/resources/wsdl/queuelog.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueueLogService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueueLogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueueLogService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public QueueLogService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueueLogService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueueLogService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns QueueLogSystemServices
     */
    @WebEndpoint(name = "QueueLogServicesEndpoint")
    public QueueLogSystemServices getQueueLogServicesEndpoint() {
        return super.getPort(QueueLogServicesEndpoint, QueueLogSystemServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueueLogSystemServices
     */
    @WebEndpoint(name = "QueueLogServicesEndpoint")
    public QueueLogSystemServices getQueueLogServicesEndpoint(WebServiceFeature... features) {
        return super.getPort(QueueLogServicesEndpoint, QueueLogSystemServices.class, features);
    }

}
