package org.example.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-13T17:22:42.064-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.example.org/demo/", name = "QueueLogSystemServices")
@XmlSeeAlso({ObjectFactory.class})
public interface QueueLogSystemServices {

    @WebMethod
    @RequestWrapper(localName = "enqueuelog", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.Enqueuelog")
    @ResponseWrapper(localName = "enqueuelogResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.EnqueuelogResponse")
    public void enqueuelog(
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.String nivel,
        @WebParam(name = "fechaEvento", targetNamespace = "")
        java.lang.String fechaEvento,
        @WebParam(name = "clase", targetNamespace = "")
        java.lang.String clase,
        @WebParam(name = "observacion", targetNamespace = "")
        java.lang.String observacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "motivoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> motivoEstado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaRespuesta", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigoEstado
    );
}
